# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Holm Hinrichs
defaults: &nodeEnv
  docker:
    - image: circleci/node:8-browsers

# Commands for rollback needed

jobs:
  build-app:
    <<: *nodeEnv
    steps:
      - checkout
      - run:
          name: prepare environment
          command: |
            npm install @angular/cli

      - run:
          name: build angular
          command: |
            cd capstone
            ng build

  test-app:
    <<: *nodeEnv
    steps:
      - checkout
      - run:
          name: prepare environment
          command: |
            npm install @angular/cli

      - run:
          name: build angular
          command: |
            cd capstone
            ng test

  lint-app:
    <<: *nodeEnv
    steps:
      - checkout
      - run:
          name: prepare environment
          command: |
            npm install @angular/cli

      - run:
          name: build angular
          command: |
            cd capstone
            ng lint





# Orchestrate or schedule a set of jobs
workflows:
  capstone:
    jobs:
      - build-app
      - test-app:
          requires: [build-app]
      - lint-app:
          requires: [test-app]



