# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Holm Hinrichs
defaults: &nodeEnv
  docker:
    - image: circleci/node:14-browsers

# Commands for rollback needed
commands:
  prepare-angulare-cli:
    steps:
      - run: 
          name: install dependencies
          command: |
            sudo npm install -g @angular/cli@latest  > /dev/null
            npm install --save-dev @angular-devkit/build-angular
            npm install @angular/compiler-cli
            npm install @angular/compiler
            ng analytics off

jobs:
  build-app:
    <<: *nodeEnv
    steps:
      - checkout
      - prepare-angulare-cli
      - run:
          name: build angular
          command: |
            cd capstone
            sudo npm link > /dev/null
            ng build

  test-app:
    <<: *nodeEnv
    steps:
      - checkout
      - prepare-angulare-cli

      - run:
          name: build angular
          command: |
            cd capstone
            sudo npm link > /dev/null
            ng test

  lint-app:
    <<: *nodeEnv
    steps:
      - checkout
      - prepare-angulare-cli

      - run:
          name: build angular
          command: |
            cd capstone
            sudo npm link > /dev/null
            ng lint





# Orchestrate or schedule a set of jobs
workflows:
  capstone:
    jobs:
      - build-app
      - test-app
      - lint-app