FROM httpd:latest
COPY ./favicon.ico /usr/local/apache2/htdocs/
COPY ./index.html /usr/local/apache2/htdocs/
COPY ./main.js /usr/local/apache2/htdocs/
COPY ./polyfills.js /usr/local/apache2/htdocs/
COPY ./runtime.js /usr/local/apache2/htdocs/
COPY ./styles.js /usr/local/apache2/htdocs/
COPY ./vendor.js /usr/local/apache2/htdocs/
EXPOSE 80:80
